# Site settings
-title: Sim & Han
-email: shks9003@hanmail.net , masteryoh@naver.com
-author: Sim, Han
+title: C++
+email: shks9003@hanmail.net , masteryoh@naver.com
+author: Sim, Han
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
-baseurl: ""
-url: "http://pixyll.com"
+baseurl: ""
+url: "http://pixyll.com"
+
+# Google analytics
google_analytics:
-animated: false
+
+# Optional features
+animated: false
show_related_posts: false
+show_post_footers: false
# Build settings
-markdown: kramdown
-permalink: pretty
-paginate: 3
+markdown: kramdown
+permalink: pretty
+paginate: 3
sass:
compressed: true
